version: "3.7"
services:
  web:
    image: php:7.2-apache
    volumes:
      - ./server:/var/www/html
    ports:
      - "8080:80"
  mysql:
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
    env_file: db.env
