version: "3.7"
services:
  web:
    build:
      dockerfile: php.Dockerfile
      context: .
    image: wordpress-ready
    volumes:
      - ./server:/var/www/html
    ports:
      - "8080:80"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    env_file: db.env
